### ISSUE TITLE
Youtube is broken? Or is it the request?

### ISSUE THREAD

**Issue by FranciscodeMaussion** [sigma67/spotifyplaylist_to_gmusic#3]
Im getting the following error when trying to convert a playlist, I've printed the res variable to make it easier.
```
{'videoId': 'F4NTvcdr4d0', 'title': 'Your Song', 'artist': 'Elisa Mosel', 'duration': 'Piano Dinner Music', 'resultType': 'song'}
Traceback (most recent call last):
  File "YouTube.py", line 163, in <module>
    main()
  File "YouTube.py", line 155, in main
    videoIds = ytmusic.search_songs(playlist['tracks'])
  File "YouTube.py", line 68, in search_songs
    targetSong = self.get_best_fit_song_id(result, song)
  File "YouTube.py", line 29, in get_best_fit_song_id
    duration = int(durationItems[0]) * 60 + int(durationItems[1])
ValueError: invalid literal for int() with base 10: 'Piano Dinner Music'
```

**Comment by FranciscodeMaussion** [comment]
Think that this is a ytmusicapi issue

**Comment by FranciscodeMaussion** [comment]
Confirmed It was a dependency issue
