### ISSUE TITLE
KeyError: 'google' during setup

### ISSUE THREAD

**Issue by kiikoh** [sigma67/spotifyplaylist_to_gmusic#4]
Traceback (most recent call last):
  File "Setup.py", line 8, in <module>
    settings['google']['mobileclient'] = api.perform_oauth(open_browser=True).to_json()
  File "/mnt/c/Users/kyled/Documents/spotifyplaylist_to_gmusic/settings.py", line 14, in __getitem__
    return config[key]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'google'

**Comment by kiikoh** [comment]
This is my error. For anyone else with the same issue you must clone the settings.ini.example and fill in credentials for spotify like the readme says
